M-extension support for SERV
olofk/serv pull request #60
Opened 2021-08-17 21:06 UTC by zeeshanrafique23

This project was the part of GSoC'21. Completed by @zeeshanrafique23  under the mentorship of @olofk.

The rtl of  M-extension and changes made in serv are verified with RISC-V compliance tests. Follow the README to run the tests.

The parent repository of MDU can be found here: https://github.com/zeeshanrafique23/mdu.git

To run the serv with M-extension you have to add mdu in [fusesoc](https://github.com/olofk/fusesoc) core list, run this command to check existing core:
```
fusesoc core list
```
and to add mdu as a fusesoc core run this command:
```
fusesoc library add mdu https://github.com/zeeshanrafique23/mdu.git
```

Now run this command to build the serv core with mdu:
```
fusesoc run --target=verilator_tb servant --MDU --vcd
```
`--vcd` flag will generate a `.vcd` file to see the wave forms.

2021-08-19 09:47 UTC, olofk requested changes
Looks good! Most of the changes are just renaming and a little cleaning up.

2021-08-19 09:47 UTC, olofk commented on rtl/serv_bufreg.v
> +   output wire [31:0] o_mdu_rs1);
Rename o_mdu_rs1 to o_ext_rs1 instead since this can potentially be shared between different extensions

2021-08-19 09:47 UTC, olofk commented on rtl/serv_decode.v
> +   output reg [2:0] o_mdu_opcode,
Let's rename o_mdu_opcode to o_ext_funct3 to show what the value comes from and that the signal can be useful for multiple extensions

2021-08-19 09:47 UTC, olofk commented on rtl/serv_mem_if.v
> +       wire mdu_rd = i_mdu_op & (dat_valid ? dat_cur : signbit & i_signed);
I think that dat_valid will always be raised for MDU operations. Please check if we can simplify this expression to just `i_mdu_op & dat_cur`

2021-08-19 09:47 UTC, olofk commented on rtl/serv_rf_top.v
>      /* Register signals before or after the decoder
Since we have moved the MDU out from SERV, I think we should change the documentation to say that this parameter enables the interface for connecting and MDU

2021-08-19 09:47 UTC, olofk commented on rtl/serv_rf_top.v
> +
I want all outputs to start with `o_` and all inputs to start with `i_`. I also want the names to have either `mdu` in the name if they are MDU-specific, or `ext` if they can be used for other extensions. But not both. As I see it only the valid signal is MDU-specific so I want that one to be `o_mdu_valid` and then ext for the rest, e.g. o_ext_rs2 or i_ext_rd

2021-08-19 09:47 UTC, olofk commented on rtl/serv_top.v
> +
Remove added whitespace

2021-08-19 09:47 UTC, olofk commented on rtl/serv_top.v
> -
Restore removed line

2021-08-19 09:47 UTC, olofk commented on rtl/serv_top.v
> -
Restore removed line

2021-08-19 09:47 UTC, olofk commented on serv.core
> +    description: Enables RISC-V standard M-extension
Enables interface for RISC-V standard M-extension

2021-08-19 09:47 UTC, olofk commented on servant.core
> +    depend : {serv, mdu}
Use [ ] instead of { }. I actually didn't know it was allowed to use { }. Seems to work fine but made me a bit confused :)

2021-08-19 10:38 UTC, zeeshanrafique23 commented on rtl/serv_rf_top.v
> +
Got it, I think the inputs should be extension-specific right? because these can come from other extensions as well.
`i_mdu_rd` and `i_mdu_ready`

2021-08-19 10:46 UTC, olofk commented on rtl/serv_rf_top.v
> +
Actually, I think we only need one of those for multiple extensions. Only one extension can be active at the same time, and the *_valid signal (e.g. mdu_valid) indicates which extension is active, so only that one should respond.

2021-08-19 10:51 UTC, olofk commented on rtl/serv_rf_top.v
> +
But I guess it's really just a matter of taste. If we have one signal (i_mdu_ready) we will need to have an expression like `ext_rd = (mdu_valid & mdu_ready) | (ext2_valid & ext2_ready)` outside of SERV but if we have separate signals the same expression will be inside of SERV. So it doesn't really matter much in practice but I see a way to keep the number of pins down on SERV which I think is good

2021-08-19 10:59 UTC, zeeshanrafique23 commented on rtl/serv_rf_top.v
> +
Great thanks for the clarification.

2021-08-19 13:24 UTC, zeeshanrafique23 commented
Thanks for reviewing, the code is modified according to the requested changes.

2021-08-19 13:38 UTC, olofk requested changes
Close now, but I missed one thing from my first review

2021-08-19 13:38 UTC, olofk commented on servant.core
> +      - MDU
This should also be "- mdu? (MDU=1)"

2021-08-19 13:38 UTC, olofk commented on rtl/serv_rf_top.v
> +endgenerate
I just realized that we need to move this generate block inside serv_top.v so that we can expose the extension interface for designs that uses serv_top directly instead of serv_rf_top (e.g. serving)

2021-08-19 13:42 UTC, zeeshanrafique23 commented on servant.core
> +      - MDU
Oh yes, this should be.

2021-08-19 14:08 UTC, zeeshanrafique23 commented on rtl/serv_rf_top.v
> +endgenerate
Done :)

2021-08-19 19:01 UTC, zeeshanrafique23 commented on rtl/serv_top.v
> -
Resolved?

2021-08-20 21:31 UTC, merged

2021-08-20 21:31 UTC, olofk commented
Awesome! I have nothing more to complain about now. :) Well done and thank you for your contributions